#HERI Variables

#ADMIN VARS
ADMINVARS<-c("ACE","SUBJID","YEAR","ACERECODE")

#Work Vars
WORKVARS<-c("PRINACT","FULLSTAT","ACADRANK","TENURE", "COURSENUM","HPW01","HPW02","HPW03","HPW04","HPW05","HPW06","HPW07","HPW08","HPW09","HPW10","HPW11","HPW12","HPW13","GENACT01","APPTYR","TENUREYR")

#Salary Vars
SALARYVARS<-c("SALARY","SALARYBASE","SALARY12", "SALARYSOURCE01","SALARYSOURCE02","SALARYSOURCE03","SALARYSOURCE04")

#Inst Vars
INSTVARS<-c("INSTDESCR03","INSTDESCR08","INSTOPN10","INSTOPN11", "DEPT","DEPTDISC", "INSTTYPE","MAJORA","DEPTA","INSTCONT","SELECTIVITY","CARNEGIE")   

#Background Vars
BACKVARS<-c("DEGEARN","DEGWORK","GENACT02","AGE","BIRTHYR","DEGYR", "NCHILD1","NCHILD2","MARITAL","SEX","NATENGSP","RACEGROUP")

#Attitude Vars
ATTITUDEVARS<-c("IMPTRTS1","IMPTRTS2","IMPTRTS3", "AFFACT02","AFFACT04")

#Other Vars
OTHERVARS<-c("ADMCHAIR","ADMDEAN","ADMPRES","ADMVP","ADMPROVOST","ADMOTHER","ADMNA","CRSTYPE01","CRSENROLL01","GENACT03","GENACT04", "PASTACT01","PASTACT02","PASTACT03","PASTACT04", "RESTYPE", "STATE","OBEREG")

# Factor Vars (I create this one later)
PROFDEVVARS<-c("PROFDEV01","PROFDEV02","PROFDEV03","PROFDEV04","PROFDEV05","PROFDEV06","PROFDEV07")  
# HERI creased these factor variables
FACTORVARS<-c("PRODUCTIVITY", "STRESS", "SATIS_WORKPLACE","SATIS_COMPENSATION")
PRODUCTIVITYVARS<-c("PUBLISH01","PUBLISH02","PUBLISH03","PUBLISH04","PUBLISH05","PUBLISH06")
STRESSVARS<-c("STRESS11","STRESS13","STRESS15","STRESS20","STRESS25")
SATISVARS<-c("SATIS01","SATIS02","SATIS03","SATIS04","SATIS05","SATIS06","SATIS07","SATIS08","SATIS09","SATIS10","SATIS11","SATIS12","SATIS13","SATIS14","SATIS15","SATIS16","SATIS17","SATIS18","SATIS19","SATIS20")  
              
# Part-time Vars
PTVARS<-c("CCSTATUS","CCRANK","PTCHOICE","PTWORKFT","PTTSEEK","PTCAREER","PTREASON01","PTREASON02","PTREASON03","PTREASON04","PTREASON05","PTREASON06","PTREASON07","PTRESOURCES01","PTRESOURCES02","PTRESOURCES03","PTRESOURCES04","PTRESOURCES05","PTOPN01","PTOPN02","PTOPN03","PTOPN04","PTOPN05","PTOPN06","PTOPN07","PTOPN08","PTOPN09","PTOPN10","PTTEACH","PTSALARY","PTPAY")   

# My vars
#"SALARYALL","BIGLAN","BIGLAN2","BIGLAN3","MARITAL2","RACEGROUP2","NCHILD3","PROFDEVFAC","HEALTHBENEFITS","RETIREBENEFITS"